// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbkU0-JWMUXHcMEwkY7aVyFTG5iHut3yo',
    appId: '1:204382690853:web:b03907cd19b1ddfd9b69cc',
    messagingSenderId: '204382690853',
    projectId: 'shoe-app-600f2',
    authDomain: 'shoe-app-600f2.firebaseapp.com',
    storageBucket: 'shoe-app-600f2.appspot.com',
    measurementId: 'G-DFSRRJXXJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAIpfCRr-vd53_ny_qP5xGA3na0OgarpM',
    appId: '1:204382690853:android:b1c37f0dc2e3f3fa9b69cc',
    messagingSenderId: '204382690853',
    projectId: 'shoe-app-600f2',
    storageBucket: 'shoe-app-600f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsfi2KBxnkoui2D7SmizWoKWqXOZNP0dY',
    appId: '1:204382690853:ios:7961f56758df236f9b69cc',
    messagingSenderId: '204382690853',
    projectId: 'shoe-app-600f2',
    storageBucket: 'shoe-app-600f2.appspot.com',
    iosBundleId: 'com.example.lydia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsfi2KBxnkoui2D7SmizWoKWqXOZNP0dY',
    appId: '1:204382690853:ios:7961f56758df236f9b69cc',
    messagingSenderId: '204382690853',
    projectId: 'shoe-app-600f2',
    storageBucket: 'shoe-app-600f2.appspot.com',
    iosBundleId: 'com.example.lydia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbkU0-JWMUXHcMEwkY7aVyFTG5iHut3yo',
    appId: '1:204382690853:web:203ea25d9b9158379b69cc',
    messagingSenderId: '204382690853',
    projectId: 'shoe-app-600f2',
    authDomain: 'shoe-app-600f2.firebaseapp.com',
    storageBucket: 'shoe-app-600f2.appspot.com',
    measurementId: 'G-2RZ39F7HT6',
  );
}
